"""initial schema

Revision ID: fca6b463a8aa
Revises: 
Create Date: 2026-03-31 01:27:25.987881

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fca6b463a8aa'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('groups',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('qa_sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=True),
    sa.Column('group_id', sa.BigInteger(), nullable=True),
    sa.Column('llm_model', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('messages',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('group_id', sa.BigInteger(), nullable=False),
    sa.Column('sender_id', sa.BigInteger(), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('reply_to_id', sa.BigInteger(), nullable=True),
    sa.Column('reply_to_group_id', sa.BigInteger(), nullable=True),
    sa.Column('message_type', sa.String(), nullable=False),
    sa.Column('raw_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('edited_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.PrimaryKeyConstraint('id', 'group_id')
    )
    op.create_table('pending_slice_messages',
    sa.Column('group_id', sa.BigInteger(), nullable=False),
    sa.Column('message_id', sa.BigInteger(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.PrimaryKeyConstraint('group_id', 'message_id')
    )
    op.create_table('slices',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('group_id', sa.BigInteger(), nullable=False),
    sa.Column('time_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('time_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('pg_done', sa.Boolean(), nullable=False),
    sa.Column('qdrant_done', sa.Boolean(), nullable=False),
    sa.Column('llm_done', sa.Boolean(), nullable=False),
    sa.Column('embedding_model', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sync_jobs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('group_id', sa.BigInteger(), nullable=False),
    sa.Column('from_ts', sa.DateTime(timezone=True), nullable=True),
    sa.Column('to_ts', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('checkpoint_message_id', sa.BigInteger(), nullable=True),
    sa.Column('checkpoint_ts', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('terms',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('word', sa.String(), nullable=False),
    sa.Column('variants', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('meanings', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('examples', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('needs_review', sa.Boolean(), nullable=False),
    sa.Column('group_id', sa.BigInteger(), nullable=True),
    sa.Column('llm_model', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('topics',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('group_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('summary_version', sa.Integer(), nullable=False),
    sa.Column('llm_model', sa.String(), nullable=True),
    sa.Column('time_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('time_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('slice_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('qa_context',
    sa.Column('qa_session_id', sa.Uuid(), nullable=False),
    sa.Column('slice_id', sa.Uuid(), nullable=False),
    sa.Column('similarity', sa.Float(), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['qa_session_id'], ['qa_sessions.id'], ),
    sa.ForeignKeyConstraint(['slice_id'], ['slices.id'], ),
    sa.PrimaryKeyConstraint('qa_session_id', 'slice_id')
    )
    op.create_table('slice_messages',
    sa.Column('slice_id', sa.Uuid(), nullable=False),
    sa.Column('message_id', sa.BigInteger(), nullable=False),
    sa.Column('group_id', sa.BigInteger(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['slice_id'], ['slices.id'], ),
    sa.PrimaryKeyConstraint('slice_id', 'message_id', 'group_id')
    )
    op.create_table('slice_topics',
    sa.Column('slice_id', sa.Uuid(), nullable=False),
    sa.Column('topic_id', sa.Uuid(), nullable=False),
    sa.Column('similarity', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['slice_id'], ['slices.id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ),
    sa.PrimaryKeyConstraint('slice_id', 'topic_id'),
    sa.UniqueConstraint('slice_id')
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS ix_messages_text_fts "
        "ON messages USING GIN (to_tsvector('simple', coalesce(text, '')))"
    )
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    op.execute(
        "CREATE INDEX IF NOT EXISTS ix_terms_word_trgm "
        "ON terms USING GIN (word gin_trgm_ops)"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP INDEX IF EXISTS ix_messages_text_fts")
    op.execute("DROP INDEX IF EXISTS ix_terms_word_trgm")
    op.drop_table('slice_topics')
    op.drop_table('slice_messages')
    op.drop_table('qa_context')
    op.drop_table('topics')
    op.drop_table('terms')
    op.drop_table('sync_jobs')
    op.drop_table('slices')
    op.drop_table('pending_slice_messages')
    op.drop_table('messages')
    op.drop_table('qa_sessions')
    op.drop_table('groups')
    # ### end Alembic commands ###
